In [1]:
import tensorflow as tf #(1)

mnist = tf.keras.datasets.mnist #(2)
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print("* shape train:", x_train.shape, y_train.shape)
print("* shape test:", x_test.shape, y_test.shape)
print("* test data:\n", x_test)

11490434/11490434 [==============================] - 3s 0us/step
* shape train: (60000, 28, 28) (60000,)
* shape test: (10000, 28, 28) (10000,)
* test data:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [2]:
model = tf.keras.models.Sequential([ #(3)
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer="Adam", #(4)
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
    )

hist= model.fit(x_train, y_train, epochs=5) #(5)

model.evaluate(x_test, y_test, verbose=2) #(6)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 2.6409 - accuracy: 0.8553
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4002 - accuracy: 0.9043
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3054 - accuracy: 0.9231
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2560 - accuracy: 0.9351
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2381 - accuracy: 0.9388
313/313 - 0s - loss: 0.2571 - accuracy: 0.9412 - 331ms/epoch - 1ms/step


[0.25707724690437317, 0.9412000179290771]

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print("* shape train:", x_train.shape, y_train.shape)
print("* shape test:", x_test.shape, y_test.shape)
# print("* test data:\n", x_test)

11490434/11490434 [==============================] - 6s 1us/step
* shape train: (60000, 28, 28) (60000,)
* shape test: (10000, 28, 28) (10000,)


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.compile(optimizer="Adam",
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
    )
# model.compile(optimizer="Adam", loss="mse", metrics=["mae"])

In [ ]:
hist= model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 2.8976 - accuracy: 0.8702
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4013 - accuracy: 0.9109
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3006 - accuracy: 0.9276
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2560 - accuracy: 0.9368
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2353 - accuracy: 0.9405


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.2875 - accuracy: 0.9336 - 325ms/epoch - 1ms/step


[0.2875145375728607, 0.9336000084877014]